server.port=8082

#For below line is only for docker configuration
spring.datasource.url=jdbc:mysql://mysql:3306/ewallet?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

#Below line is for MySQL configuration
#spring.datasource.url=jdbc:mysql://localhost:3306/ewallet?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Harsh@12345
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Production-safe settings
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

logging.level.root=INFO